version: '3.8'

services:
    db:
        container_name: postgres
        image: postgres:15.1-alpine3.17
        ports:
            - '${DB_PORT}:${DB_PORT}'
        environment:
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

networks:
    default:
        name: task-mgmt-app-network
        external: false
